### PR TITLE
fix(NA) - Add missing sample rate value to generated metric line.

### LINKED ISSUE #6: Missing sample rate value in generated metric line.
The sample rate should be added to the end of the generated metric line.

### PR DESCRIPTION
**Pull request by miguelcnf**
Should fix #6

### CODE REVIEW

File: core/src/main/java/com/statful/client/core/message/MessageBuilder.java [hunk 1]
```diff
@@ -24,6 +24,7 @@
     private String value;
     private long timestamp;
     private AggregationFrequency aggregationFrequency = AggregationFrequency.FREQ_10;
+    private int sampleRate;
```
Comment (reistiago) [inline core/src/main/java/com/statful/client/core/message/MessageBuilder.java]: This can behave as a default of 0 which is strange. Possibly set the default value (100), change to Integer and use a null or Optional?

File: core/src/main/java/com/statful/client/core/message/MessageBuilder.java [hunk 2]
```diff
@@ -164,6 +176,8 @@ public String build() {
             sb.append(aggregationFrequency.getValue());
         }
 
+        sb.append(" ").append(sampleRate);
```
Comment (reistiago) [inline core/src/main/java/com/statful/client/core/message/MessageBuilder.java]: Given the above comment, probably an if or an optional is missing here
